services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - FLASK_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
